/// Flutter icons ScaleIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScaleIcon
///      fonts:
///       - asset: fonts/ScaleIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ScaleIcon {
  ScaleIcon._();

  static const _kFontFam = 'ScaleIcon';

  static const IconData weight = const IconData(0xe800, fontFamily: _kFontFam);
}
